objects/BankAccount__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>BankAccount</relationshipLabel>
        <relationshipName>BankAccount</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BankAccount</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BankAccount</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OAC_Transactions__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>From_Account_External_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>From Account External Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>OAC Transactions</relationshipLabel>
        <relationshipName>OAC_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>From_Bank_Account_External_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>From Bank Account External Id</label>
        <referenceTo>BankAccount__c</referenceTo>
        <relationshipLabel>OAC Transactions</relationshipLabel>
        <relationshipName>OAC_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Remarks__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Remarks</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To_Account_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>To Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Transaction Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Transaction Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>OAC Transactions</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>OAC Transactions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OAC Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AllBankAcctsTransactionsControllerTest.cls
@isTest
public class AllBankAcctsTransactionsControllerTest {
  
    
    @isTest
    public static void function(){
        
        Account acc = new Account(Name='Test');
        insert acc;
        
        BankAccount__c bnkAcc= new BankAccount__c();
        bnkAcc.Name ='Test';
        bnkAcc.Account__c=acc.id;
        
        insert bnkAcc;
        
        OAC_Transactions__c tran = new OAC_Transactions__c(Transaction_Date__c = Date.today(),
                                                       Remarks__c = 'test remark',
                                                       Transaction_Type__c = 'test',
                                                       Amount__c=43,
                                                       To_Account_Name__c = acc.id,
                                                       From_Account_External_Id__c =acc.Id,
                                                       From_Bank_Account_External_Id__c = bnkAcc.id);
        
        
        ApexPages.StandardController sc = new ApexPages.StandardController(bnkAcc);
        
        
        PageReference pageRef = Page.Transactions;
        pageRef.getParameters().put('id', String.valueOf(bnkAcc.Id));
        Test.setCurrentPage(pageRef);
        
        AllBankAccountsTransactionsController transactions = new AllBankAccountsTransactionsController(sc);
        transactions.cancel();
    }
}