objects/BankAccount__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>BankAccount</relationshipLabel>
        <relationshipName>BankAccount</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BankAccount</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BankAccount</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Relationship_Bank_Account__c.object
<CustomObject>
    <fields>
        <fullName>BankAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bank Account</label>
        <referenceTo>BankAccount__c</referenceTo>
        <relationshipLabel>Relationship-Bank Account</relationshipLabel>
        <relationshipName>Relationship_Bank_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Relationship-Bank Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Relationship-Bank Account	 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship-Bank Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RelationshipBATriggerhandler_test.cls
@isTest
private class RelationshipBATriggerhandler_test{
    
    static testmethod Void testrelationshipTriggerHandler(){
        
        /*Create RelationShip Object for Testing */
        Account objAccount = new Account();
        objAccount.Name = 'Test Account';
        insert objAccount;
        
        BankAccount__c objBankAccount = new BankAccount__c();
        objBankAccount.Account__c = objAccount.Id;
        objBankAccount.Name = 'Test Bank';
        insert objBankAccount;
         
        Relationship_Bank_Account__c rel = new Relationship_Bank_Account__c();
        rel.BankAccount__c = objBankAccount.Id;
        rel.Name = 'test';
        insert rel;
        
        rel.Name ='sss';
        update rel;
        rel= [select External_Id__c from Relationship_Bank_Account__c where Id=:rel.id];
        System.assertEquals(true, rel.External_Id__c !=null);     // Checking if we are getting id In assert equal 
        
    }
}