objects/BankAccount__c.object
<CustomObject>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>This is a Unique Id to store the Id of the external system when mapping back.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>ExternalId</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>BankAccount</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BankAccount</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BankAccountTriggerHandler.cls
// Trigger handler class to update the Contact External Id when it is null

Public Class BankAccountTriggerHandler extends TriggerHandler {


    public BankAccountTriggerHandler() {
    
    }
    
    //All the functionality which needs to be executed afterinsert goes
    // into this method.
    Protected override void afterInsert() {
    updateExternalId();
    }
    
    //All the functionality which needs to be executed afterupdate goes
    // into this method.
    Protected override void afterUpdate() {
    updateExternalId();
    }
    
 /* private methods */
 /*Method to update external id */
 
    private void updateExternalId() {
    List <BankAccount__c> bnList = new List <BankAccount__c> ();
    for (BankAccount__c bn: (List < BankAccount__c> ) Trigger.new) {
        
        //Execute this only when the external id is null
        if (bn.ExternalId__c== null) {
            BankAccount__c bc = new BankAccount__c(ID = bn.id);
            bc.ExternalId__c= bn.id;
            bnList.add(bc);
        }
       
        if (bnList.size() > 0) {
            update bnList;
        }
    
      }
    }//End updateExternalId
    

}//End class