objects/BankAccount__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>BankAccount</relationshipLabel>
        <relationshipName>BankAccount</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>This is a Unique Id to store the Id of the external system when mapping back.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>ExternalId</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>BankAccount</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BankAccount</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BankAccountTriggerhandler_test.cls
@isTest
private class BankAccountTriggerhandler_test{

  static testmethod Void testBankAccountTriggerHandler(){
    
  /*Create Bank Accunt Object for Testing */
        
        //Insert 
        Account acct = new Account();
        acct.Name='TestAccount';
        insert acct ;
        
        //Insert 
        BankAccount__c bank = new BankAccount__c();
        bank.name='TestBank';
        bank.Account__c= acct.id;
        insert bank;
        bank = [select ExternalId__c from BankAccount__c where Id=:bank.id];
        System.assertEquals(true, bank.ExternalId__c !=null);     // Checking if we are getting id In assert equal 
        
        //Update 
        bank.name='TestBank1';
        update bank;
        bank= [select ExternalId__c  from BankAccount__c  where Id=:bank.id];
        System.assertEquals(true, bank.ExternalId__c  !=null);     // Checking if we are getting id In assert equal 
        
        
      }
  }