objects/Category_History__c.object
<CustomObject>
    <fields>
        <fullName>Category_Score__c</fullName>
        <label>Category Score</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date_Computed__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Date Computed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Model_Category_DefinitionLookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Model Category Definition</label>
        <referenceTo>Model_Category_Definition__c</referenceTo>
        <relationshipLabel>Category History</relationshipLabel>
        <relationshipName>Category_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Model_Category_Definition__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Model Category Definition</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Score</label>
        <referenceTo>Score__c</referenceTo>
        <relationshipLabel>Category History</relationshipLabel>
        <relationshipName>Category_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Category History</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Category History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Category History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Indicator_Value__c.object
<CustomObject>
    <description>This is used to store the Scores at the lowest level ( at the Indicator level )</description>
    <fields>
        <fullName>Model_Indicator_Definition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Model Indicator Definition</label>
        <referenceTo>Model_Indicator_Definitions__c</referenceTo>
        <relationshipLabel>Indicator Values</relationshipLabel>
        <relationshipName>Indicator_Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Note__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Note</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Score</label>
        <referenceTo>Score__c</referenceTo>
        <relationshipLabel>Indicator Values</relationshipLabel>
        <relationshipName>Indicator_Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <label>Indicator Value</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Indicator Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indicator Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Model_Category_Definition__c.object
<CustomObject>
    <fields>
        <fullName>Category_Score__c</fullName>
        <label>Category Score</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Display_Order__c</fullName>
        <label>Display Order</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Model_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Model Version</label>
        <referenceTo>Model_Version__c</referenceTo>
        <relationshipName>Master_Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Model Category Definition</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Model Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Model Category Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Model_Indicator_Definitions__c.object
<CustomObject>
    <fields>
        <fullName>Display_Order__c</fullName>
        <label>Display Order</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Indicator_Weight__c</fullName>
        <label>Indicator Weight</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Model_Sub_Category_Definition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Model Sub Category Definition</label>
        <referenceTo>Model_Sub_Category_Definition__c</referenceTo>
        <relationshipLabel>Model Indicator Definitions</relationshipLabel>
        <relationshipName>Model_Score_Labels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Score_Labels__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Score Labels</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <defaultValue>&apos;V 1.0&apos;</defaultValue>
        <encryptionScheme>None</encryptionScheme>
        <label>Version</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Model Indicator Definition</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Model Indicator Definition  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Model Indicator Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Model_Sub_Category_Definition__c.object
<CustomObject>
    <fields>
        <fullName>Display_Order__c</fullName>
        <label>Display Order</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Model_Category_Definition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Model Category Definition</label>
        <referenceTo>Model_Category_Definition__c</referenceTo>
        <relationshipLabel>Model Sub Category Definitions</relationshipLabel>
        <relationshipName>Model_Sub_Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Category_Score__c</fullName>
        <label>Sub Category Score</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sub_Category_Weight__c</fullName>
        <label>Sub Category Weight</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Model Sub Category Definition</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Model Sub Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Model Sub Category Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Model_Version__c.object
<CustomObject>
    <label>Model Version</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Model Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Model Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Score__c.object
<CustomObject>
    <description>To store the Overall Score</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Scores</relationshipLabel>
        <relationshipName>Scores</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active_From__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Active From</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Active_To__c</fullName>
        <description>For the latest score , this field would be blank.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Active To</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Score__c</fullName>
        <label>Most Recent Score</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Version</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Score</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Score Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sub_Category_History__c.object
<CustomObject>
    <description>To store the derived sub category level Scores and the History</description>
    <fields>
        <fullName>Date_Computed__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Date Computed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Model_Category_Definition_Formula__c</fullName>
        <formula>Model_Sub_Category_DefinitionLookup__r.Model_Category_Definition__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Model Category Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Category_Definition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Model Category Definition</label>
        <referenceTo>Model_Category_Definition__c</referenceTo>
        <relationshipLabel>Sub Category History</relationshipLabel>
        <relationshipName>Sub_Category_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Model_Sub_Category_DefinitionLookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Model Sub Category Definition</label>
        <referenceTo>Model_Sub_Category_Definition__c</referenceTo>
        <relationshipLabel>Sub Category History</relationshipLabel>
        <relationshipName>Sub_Category_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Model_Sub_Category_Definition__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Model Sub Category Definition</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Score</label>
        <referenceTo>Score__c</referenceTo>
        <relationshipLabel>Sub Category History</relationshipLabel>
        <relationshipName>Sub_Category_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Category_Score__c</fullName>
        <label>Sub Category Score</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>Sub Category History</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Sub Category History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Category History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MasterScoreCalculatorTest.cls
@isTest
public class MasterScoreCalculatorTest {
	

	//public String catId;
   // public String subCatName;
    
	@testSetup
	static void testRiskEvaluationSetup(){
		
        Model_Version__c objmodelVersion = new Model_Version__c();
			objmodelVersion.Name = 'Test model Version';
			insert objModelversion;
            System.debug('>>>>>>objModelversion'+objModelversion);
        
		Account objAccount = new Account();
			objAccount.Name = 'Test Account';
            objAccount.Most_Recent_Risk_Score__c = 1.2;
            objAccount.Model_Version_Lookup__c = objmodelVersion.Id;
			insert objAccount;
            System.debug('>>>>>>objAccount'+objAccount);
        
        Score__c objScore = new Score__c();
			objScore.Name = 'Inherited Score';
			objScore.Account__c = objAccount.Id;
			objScore.Active_From__c = datetime.newInstance(2018, 12, 19, 12, 30, 0);
			objScore.Active_To__c = datetime.newInstance(2018, 12, 15, 20, 30, 0);
			objScore.Most_Recent_Score__c = 35;
			objScore.Version__c = objAccount.Model_Version_Lookup__c;
			insert objScore;
            System.debug('>>>>>>objScore'+objScore);
				
        
        Score__c objScoreRes = new Score__c();
			objScoreRes.Name = 'Residual Score';
			objScoreRes.Account__c = objAccount.Id;
			objScoreRes.Active_From__c = datetime.newInstance(2018, 12, 19, 12, 30, 0);
			objScoreRes.Active_To__c = datetime.newInstance(2018, 12, 15, 20, 30, 0);
			objScoreRes.Most_Recent_Score__c = 35;
			objScoreRes.Version__c = objAccount.Model_Version_Lookup__c;
			insert objScoreRes;
        
        
		Model_Category_Definition__c objModelCategory = new Model_Category_Definition__c();
			objModelCategory.Name = 'Regulatory';
			objModelCategory.Model_Version__c = objmodelVersion.Id;
			objModelCategory.Weight__c = 30;
			objModelCategory.Category_Score__c = 112;
            objModelCategory.Display_Order__c = 1;
			insert objModelCategory;
            System.debug('>>>>>>objModelCategory'+objModelCategory);
            //String catId = objModelCategory.Id;
		
		Model_Sub_Category_Definition__c objModelSubCat = new Model_Sub_Category_Definition__c();
			objModelSubCat.Name = 'Test Model SubCategory';
			objModelSubCat.Model_Category_Definition__c = objModelCategory.Id;
			objModelSubCat.Sub_Category_Score__c = 211;
			objModelSubCat.Sub_Category_Weight__c = 20;
        	objModelSubCat.Display_Order__c = 2;
			insert objModelSubCat;
            System.debug('>>>>>>objModelSubCat'+objModelSubCat);
            //String subCatName = objModelSubCat.Name;
			
		Model_Indicator_Definitions__c objModelIndDef = new Model_Indicator_Definitions__c();
			objModelIndDef.Name = 'Test Model Indicator';
			objModelIndDef.Indicator_Weight__c = 20;
			objModelIndDef.Model_Sub_Category_Definition__c = objModelSubCat.Id;
			objModelIndDef.Score_Labels__c = 'Test Score Label';
			objModelIndDef.Display_Order__c = 1;
			insert objModelIndDef;
            System.debug('>>>>>>objModelIndDef'+objModelIndDef);
		
		
		
		Category_History__c objCatHistory = new Category_History__c();
			objCatHistory.Name = 'Test Category History';
			objCatHistory.Category_Score__c = 45;
			objCatHistory.Date_Computed__c = System.today();
			objCatHistory.Model_Category_DefinitionLookup__c = objModelCategory.Id;
			objCatHistory.Score__c = objScore.Id;
			insert objCatHistory;
            System.debug('>>>>>>objCatHistory'+objCatHistory);
		
		Sub_Category_History__c objSubCatHistory = new Sub_Category_History__c();
			objSubCatHistory.Name = 'Test Sub Catgeory History';
			objSubCatHistory.Date_Computed__c = Date.newInstance(2018, 12, 19);
			objSubCatHistory.Model_Category_Definition__c = objModelCategory.Id;
			//objSubCatHistory.Model_Category_Definition_Formula__c
			objSubCatHistory.Model_Sub_Category_DefinitionLookup__c = objModelSubCat.Id;
			objSubCatHistory.Score__c = objScore.Id;
			objSubCatHistory.Sub_Category_Score__c = 30;
			insert objSubCatHistory;
            System.debug('>>>>>>objSubCatHistory'+objSubCatHistory);
		
		Indicator_Value__c objIndicatorValue = new Indicator_Value__c();
			objIndicatorValue.Name = 'Test Indicator Value';
			objIndicatorValue.Note__c = 'Test Indicator Note';
			objIndicatorValue.Model_Indicator_Definition__c = objModelIndDef.Id;
			objIndicatorValue.Score__c = objScore.Id;
			objIndicatorValue.Value__c = 90;
            insert objIndicatorValue;
        
           	objIndicatorValue.Name = 'Test Indicator';
             objIndicatorValue.Value__c = 20;


            update objIndicatorValue;
	}
	
	@isTest
	static void testEvaluation(){
        
        Account objAccount = new Account();
        objAccount.Name = 'Test Account';
        objAccount.Is_Master_Account__c= true ;
        insert objAccount;
        
        Account accs = [Select Program_ID__c, id ,(select Id FROM Scores__r where name ='Residual Score' ORDER BY createdDate  DESC LIMIT 1) from Account where  Is_Master_Account__c = false];
        System.debug([select Id,Account__c FROM Score__c]);
        
		Test.startTest();
        	ApexPages.currentPage().getParameters().put('Id',objAccount.id);
        	MasterScoreCalculator  mc = new MasterScoreCalculator();
        	mc.doStart();
        Test.stopTest();
        
    }
    
    
    

}