objects/Category_History__c.object
<CustomObject>
    <fields>
        <fullName>Category_Score__c</fullName>
        <label>Category Score</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date_Computed__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Date Computed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Model_Category_DefinitionLookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Model Category Definition</label>
        <referenceTo>Model_Category_Definition__c</referenceTo>
        <relationshipLabel>Category History</relationshipLabel>
        <relationshipName>Category_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Model_Category_Definition__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Model Category Definition</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Score</label>
        <referenceTo>Score__c</referenceTo>
        <relationshipLabel>Category History</relationshipLabel>
        <relationshipName>Category_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Category History</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Category History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Category History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Indicator_Value__c.object
<CustomObject>
    <description>This is used to store the Scores at the lowest level ( at the Indicator level )</description>
    <fields>
        <fullName>Model_Indicator_Definition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Model Indicator Definition</label>
        <referenceTo>Model_Indicator_Definitions__c</referenceTo>
        <relationshipLabel>Indicator Values</relationshipLabel>
        <relationshipName>Indicator_Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Score</label>
        <referenceTo>Score__c</referenceTo>
        <relationshipLabel>Indicator Values</relationshipLabel>
        <relationshipName>Indicator_Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Indicator Value</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Indicator Value Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indicator Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Model_Category_Definition__c.object
<CustomObject>
    <fields>
        <fullName>Category_Score__c</fullName>
        <label>Category Score</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Model Category Definition</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Model Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Model Category Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Model_Indicator_Definitions__c.object
<CustomObject>
    <fields>
        <fullName>Indicator_Weight__c</fullName>
        <label>Indicator Weight</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Model_Sub_Category_Definition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Model Sub Category Definition</label>
        <referenceTo>Model_Sub_Category_Definition__c</referenceTo>
        <relationshipLabel>Model Indicator Definitions</relationshipLabel>
        <relationshipName>Model_Score_Labels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Score_Labels__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Score Labels</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Model Indicator Definition</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Model Indicator Definition  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Model Indicator Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Model_Sub_Category_Definition__c.object
<CustomObject>
    <fields>
        <fullName>Model_Category_Definition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Model Category Definition</label>
        <referenceTo>Model_Category_Definition__c</referenceTo>
        <relationshipLabel>Model Sub Category Definitions</relationshipLabel>
        <relationshipName>Model_Sub_Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Category_Score__c</fullName>
        <label>Sub Category Score</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sub_Category_Weight__c</fullName>
        <label>Sub Category Weight</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Model Sub Category Definition</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Model Sub Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Model Sub Category Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Score__c.object
<CustomObject>
    <description>To store the Overall Score</description>
    <label>Score</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Score Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sub_Category_History__c.object
<CustomObject>
    <description>To store the derived sub category level Scores and the History</description>
    <fields>
        <fullName>Date_Computed__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Date Computed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Model_Category_Definition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Model Category Definition</label>
        <referenceTo>Model_Category_Definition__c</referenceTo>
        <relationshipLabel>Sub Category History</relationshipLabel>
        <relationshipName>Sub_Category_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Model_Sub_Category_DefinitionLookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Model Sub Category Definition</label>
        <referenceTo>Model_Sub_Category_Definition__c</referenceTo>
        <relationshipLabel>Sub Category History</relationshipLabel>
        <relationshipName>Sub_Category_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Model_Sub_Category_Definition__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Model Sub Category Definition</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Score</label>
        <referenceTo>Score__c</referenceTo>
        <relationshipLabel>Sub Category History</relationshipLabel>
        <relationshipName>Sub_Category_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Category_Score__c</fullName>
        <label>Sub Category Score</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>Sub Category History</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Sub Category History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Category History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ModelCategoryWrapper.cls
public class ModelCategoryWrapper {
    
    public String CategoryName{set;get;}
    public Model_Category_Definition__c modelCategory{set;get;}
    public Map<String,ModelSubCatWrapper> subCatWrapperMap{set;get;}
    public Category_History__c catHistory{set;get;}
    public Category_History__c resCatHistory{set;get;}
    public Decimal derivedCatScore{set;get;}
    public Decimal residualCatScore{set;get;}
    public Boolean isSaveCat;
    
    public ModelCategoryWrapper(){
        modelCategory = new Model_Category_Definition__c(weight__c=0);
        subCatWrapperMap = new Map<String,ModelSubCatWrapper>();
        catHistory = new Category_History__c(Category_Score__c=0);
        resCatHistory = new Category_History__c(Category_Score__c=0);
        derivedCatScore =0;
        residualCatScore =0;
        isSaveCat=false;
    }
    
    public void save(String scoreId, String resScoreId){
        
        System.debug('CatHistory score...'+CatHistory.Category_Score__c);
        System.debug('Res CatHistory score...'+resCatHistory.Category_Score__c);
        
        for(ModelCategoryWrapper.ModelSubCatWrapper msw :subCatWrapperMap.values()){
            
            //Save Sub Categories
            msw.save(scoreId,resScoreId,modelCategory.Id);
            
        }
        
        catHistory.Date_Computed__c = System.today();
        catHistory.Model_Category_DefinitionLookup__c = modelCategory.Id;
        catHistory.Score__c = scoreId;
        upsert catHistory;
        
        resCatHistory.Date_Computed__c = System.today();
        resCatHistory.Model_Category_DefinitionLookup__c = modelCategory.Id;
        resCatHistory.Score__c = resScoreId;
        upsert resCatHistory;
    }
    
    public class ModelSubCatWrapper{
        public String subCatName{set;get;}
        public Model_Sub_Category_Definition__c modelSubCat{set;get;}
        public Map<String,ModelIndicatorWrapper> indicatorWrapperMap{set;get;}
        public Sub_Category_History__c subCatHistory{set;get;}
        public Sub_Category_History__c resSubCatHistory{set;get;}
        public Decimal derivedSubCatScore{set;get;}
        public Decimal residualSubCatScore{set;get;}
        public Boolean isSaved;
        
        public ModelSubCatWrapper(String subCatId){
            modelSubCat = new Model_Sub_Category_Definition__c(Sub_Category_Weight__c=0);
            indicatorWrapperMap  = new Map<String,ModelIndicatorWrapper>();
            subCatHistory = new Sub_Category_History__c(Sub_Category_Score__c=0);
            resSubCatHistory = new Sub_Category_History__c(Sub_Category_Score__c=0);
            derivedSubCatScore = 0;
            residualSubCatScore =0;
            isSaved=false;
            modelSubCat.Sub_Category_Weight__c = 0;
        
        }
        
      public ModelSubCatWrapper(){
            subCatHistory = new Sub_Category_History__c();
        }
        
        public void save(String scoreId, String resScoreId, String catId){
            System.debug('subCatHistory score...'+subCatHistory.Sub_Category_Score__c);
            System.debug('RessubCatHistory score...'+RessubCatHistory.Sub_Category_Score__c);
            
            saveHistories(scoreId,resScoreId,catId);
            
            List<Indicator_Value__c> indicatorValues = new List<Indicator_Value__c>();
            for(ModelCategoryWrapper.ModelIndicatorWrapper miw : indicatorWrapperMap.values()){
                miw.save(scoreId,resScoreId,isSaved);
                indicatorValues.add(miw.indicatorValue);
            }
            if(!isSaved){
                insert indicatorValues;
            }
            else{
                update indicatorValues;
            }
            isSaved =true;
        }
        
        
        public void saveHistories(String scoreId, String resScoreId, String catId){
            subCatHistory.Date_Computed__c = System.Today();
            subCatHistory.Model_Sub_Category_DefinitionLookup__c = modelSubCat.id;
            
            subCatHistory.Score__c = scoreId;
            upsert subCatHistory;
            
            RessubCatHistory.Date_Computed__c = System.Today();
            RessubCatHistory.Model_Sub_Category_DefinitionLookup__c = modelSubCat.id;
            RessubCatHistory.Score__c = resScoreId;
            upsert RessubCatHistory;
        }
    }
    
    public class ModelIndicatorWrapper{
        public String labelName{set;get;}
        public Model_Indicator_Definitions__c modelIndicator{set;get;}
        public Indicator_Value__c indicatorValue{set;get;}
        
        
        public ModelIndicatorWrapper(){
            modelIndicator = new Model_Indicator_Definitions__c(Indicator_Weight__c=0);
            indicatorValue = new Indicator_Value__c();
        }
        
        public void save(String scoreId, String resScoreId,Boolean isSaved){
            indicatorValue.Score__c = scoreId;
            indicatorValue.Model_Indicator_Definition__c = modelIndicator.Id;
            indicatorValue.Name = modelIndicator.Score_Labels__c;
            if(!isSaved){
                indicatorValue.id=null;
            }
        }
    }
}