objects/Customer_Document__c.object
<CustomObject>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Annual Report</fullName>
                </value>
                <value>
                    <fullName>Application PDF</fullName>
                </value>
                <value>
                    <fullName>Articles of Incorporation</fullName>
                </value>
                <value>
                    <fullName>Articles of Organization</fullName>
                </value>
                <value>
                    <fullName>ATM Service Agreement</fullName>
                </value>
                <value>
                    <fullName>Balance Sheet</fullName>
                </value>
                <value>
                    <fullName>Business Check</fullName>
                </value>
                <value>
                    <fullName>Cashflow Statement</fullName>
                </value>
                <value>
                    <fullName>City License</fullName>
                </value>
                <value>
                    <fullName>Company Profile</fullName>
                </value>
                <value>
                    <fullName>Corporate Officers</fullName>
                </value>
                <value>
                    <fullName>Corporate Resolution</fullName>
                </value>
                <value>
                    <fullName>County License</fullName>
                </value>
                <value>
                    <fullName>Cultivation Tax Receipts</fullName>
                </value>
                <value>
                    <fullName>DBA Certificate</fullName>
                </value>
                <value>
                    <fullName>EIN Verification</fullName>
                </value>
                <value>
                    <fullName>Excise Tax Receipts</fullName>
                </value>
                <value>
                    <fullName>Federal Tax Return</fullName>
                </value>
                <value>
                    <fullName>Financial Forecast</fullName>
                </value>
                <value>
                    <fullName>Income Statement</fullName>
                </value>
                <value>
                    <fullName>Insurance Policy</fullName>
                </value>
                <value>
                    <fullName>Joint Venture Agreement</fullName>
                </value>
                <value>
                    <fullName>Key Personnel</fullName>
                </value>
                <value>
                    <fullName>Lease Agreement</fullName>
                </value>
                <value>
                    <fullName>Local Tax Receipts</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
                <value>
                    <fullName>On-site Checklist</fullName>
                </value>
                <value>
                    <fullName>On-site Inspector Report</fullName>
                </value>
                <value>
                    <fullName>Ownership Structure</fullName>
                </value>
                <value>
                    <fullName>P&amp;L Statement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>externalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>externalId</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Customer Document</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CustomerDocumentTriggerHandler.cls
public class CustomerDocumentTriggerHandler extends TriggerHandler  {
    
    public void onBeforeInsert(List<Customer_Document__c> newList){
        for(Customer_Document__c cd:newList){
            
            cd.name = cd.Document_Type__c;
        }
    }
    
    public CustomerDocumentTriggerHandler() {
    
    }
    
    // Trigger handler class to update the Customer Document External Id when it is null
    // This handler class is developed on March 5 2019
    //All the functionality which needs to be executed afterinsert goes
    // into this method.
    Protected override void afterInsert() {
        updateExternalId();
    }
    
    //All the functionality which needs to be executed afterupdate goes
    // into this method.
    Protected override void afterUpdate() {
        updateExternalId();
    }
    
 /* private methods */
 /*Method to update external id */
 
    private void updateExternalId() {
        List <Customer_Document__c> customerDocList = new List <Customer_Document__c> ();
        for (Customer_Document__c cusDoc: (List < Customer_Document__c> ) Trigger.new) {
            
            //Execute this only when the external id is null
            if (cusDoc.externalId__c== null) {
                Customer_Document__c cusDocObj = new Customer_Document__c (ID = cusDoc.id);
                cusDocObj.externalId__c= cusDoc.id;
                customerDocList.add(cusDocObj);
            }
           
            
        
          }
          
          try{
                if (customerDocList.size() > 0) {
                    update customerDocList ;
                }
          
          }catch(Exception e){
                
                system.debug('error in update ext id'+e.getMessage()+'-LineNUmber--'+e.getLineNumber());
            
          }
    }//End updateExternalId
}