objects/Customer_Document__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Documents</relationshipLabel>
        <relationshipName>Customer_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Annual Report</fullName>
                </value>
                <value>
                    <fullName>Application PDF</fullName>
                </value>
                <value>
                    <fullName>Articles of Incorporation</fullName>
                </value>
                <value>
                    <fullName>Articles of Organization</fullName>
                </value>
                <value>
                    <fullName>ATM Service Agreement</fullName>
                </value>
                <value>
                    <fullName>Balance Sheet</fullName>
                </value>
                <value>
                    <fullName>Business Check</fullName>
                </value>
                <value>
                    <fullName>Cashflow Statement</fullName>
                </value>
                <value>
                    <fullName>City License</fullName>
                </value>
                <value>
                    <fullName>Company Profile</fullName>
                </value>
                <value>
                    <fullName>Corporate Officers</fullName>
                </value>
                <value>
                    <fullName>Corporate Resolution</fullName>
                </value>
                <value>
                    <fullName>County License</fullName>
                </value>
                <value>
                    <fullName>Cultivation Tax Receipts</fullName>
                </value>
                <value>
                    <fullName>DBA Certificate</fullName>
                </value>
                <value>
                    <fullName>EIN Verification</fullName>
                </value>
                <value>
                    <fullName>Excise Tax Receipts</fullName>
                </value>
                <value>
                    <fullName>Federal Tax Return</fullName>
                </value>
                <value>
                    <fullName>Financial Forecast</fullName>
                </value>
                <value>
                    <fullName>Income Statement</fullName>
                </value>
                <value>
                    <fullName>Insurance Policy</fullName>
                </value>
                <value>
                    <fullName>Joint Venture Agreement</fullName>
                </value>
                <value>
                    <fullName>Key Personnel</fullName>
                </value>
                <value>
                    <fullName>Lease Agreement</fullName>
                </value>
                <value>
                    <fullName>Local Tax Receipts</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous</fullName>
                </value>
                <value>
                    <fullName>On-site Checklist</fullName>
                </value>
                <value>
                    <fullName>On-site Inspector Report</fullName>
                </value>
                <value>
                    <fullName>Ownership Structure</fullName>
                </value>
                <value>
                    <fullName>P&amp;L Statement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer Document</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DeleteCustomerDocumentControllerTest.cls
@isTest
public class DeleteCustomerDocumentControllerTest {
    
    static testMethod void testPage() {
	    Account testAccount = new Account(Name = 'Test');
	    insert testAccount;
	    
	    Customer_Document__c custDoc = new Customer_Document__c(
	    	Account__c=testAccount.Id,
	    	Name='Test Doc',
	    	Document_Type__c='Annual Report'
	    );
	    insert custDoc;
	    
	    // Oddly it appears one needs to create a ContentVersion object to create a ContentDocument object.
	    ContentVersion contVersion = new ContentVersion(
            Title = 'Test',
            PathOnClient = 'Test.txt',
            VersionData = Blob.valueOf('Test Content Data'),
            IsMajorVersion = true
        );
        insert contVersion;
        
        List<ContentDocument> contentDocs = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        ContentDocument contentDoc = contentDocs[0];
        
        ContentDocumentLink cdl = new ContentDocumentLink(
			ContentDocumentId = contentDoc.id,
			LinkedEntityId = custDoc.id,
			ShareType = 'V'      			
        );
        insert cdl;
            
	    Test.StartTest();
	        ApexPages.currentPage().getParameters().put('id', String.valueOf(custDoc.id));
            
            ApexPages.StandardController sc = new ApexPages.StandardController(custDoc);
        	DeleteCustomerDocumentController testPage = new DeleteCustomerDocumentController(sc);
            
            testPage.doDelete();
            testPage.goToAccount();
            
	    Test.StopTest();
		
		List<Customer_Document__c> updatedCustomerDocs = new List<Customer_Document__c>([SELECT Id FROM Customer_Document__c]);
		System.assertEquals(0, updatedCustomerDocs.size(), 'There should be no Customer Documents');
		
		List<ContentDocument> updatedContentDocs = new List<ContentDocument>([SELECT Id FROM ContentDocument]);
		System.assertEquals(0, updatedContentDocs.size(), 'There should be no Content Documents');
	    		
		List<ContentDocumentLink> updatedContentDocLinks = new List<ContentDocumentLink>([SELECT Id 
				FROM ContentDocumentLink WHERE LinkedEntityId = :custDoc.id]);
		System.assertEquals(0, updatedContentDocLinks.size(), 'There should be no Content Document Links');
	    
	}
	
}