objects/OAC_Transactions__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CreditDebit__c</fullName>
        <label>CreditDebit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Credit</fullName>
                </value>
                <value>
                    <fullName>Debit</fullName>
                </value>
                <value>
                    <fullName>tCredit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Error_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Error Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>ExternalId</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Fee__c</fullName>
        <label>Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>From_Account_External_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>From Account External Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>OAC Transactions</relationshipLabel>
        <relationshipName>OAC_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>From_Account_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>From Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>From_Bank_Account_External_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>From Bank Account External Id</label>
        <referenceTo>BankAccount__c</referenceTo>
        <relationshipLabel>OAC Transactions</relationshipLabel>
        <relationshipName>OAC_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Remarks__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Remarks</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To_Account_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>To Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To_Bank_Account_External_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>To Bank Account External Id</label>
        <referenceTo>BankAccount__c</referenceTo>
        <relationshipLabel>OAC Transactions (To Bank Account External Id)</relationshipLabel>
        <relationshipName>OAC_Transactions_To_Bank_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Transaction Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Transaction Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>OAC Transactions</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>OAC Transactions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OAC Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AllBankAccountsTransactionsController.cls
public class AllBankAccountsTransactionsController {
    public List<OAC_Transactions__c> transactionList{set;get;}
    
    
    public AllBankAccountsTransactionsController(ApexPages.StandardController controller){
        this();
    }
    
    public AllBankAccountsTransactionsController(){
        String accId = ApexPages.currentPage().getParameters().get('id');
        if(accId !=null)
            initializeRecords(accId);
    }
    
    private void initializeRecords(String accId){
        transactionList = [select Transaction_Date__c,Error_Code__c,Remarks__c,Transaction_Type__c,Amount__c,To_Account_Name__c,CreditDebit__c,ExternalId__c,Fee__c,From_Account_External_Id__c,From_Account_Name__c,To_Bank_Account_External_Id__c from OAC_Transactions__c where From_Bank_Account_External_Id__c = :accId order by Transaction_Date__c desc];
    }
    
    public PageReference cancel(){
        String accId = ApexPages.currentPage().getParameters().get('id');
        return new PageReference('/'+accId);
    }
}