objects/OAC_Transactions__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>From_Account_External_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>From Account External Id</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>OAC Transactions</relationshipLabel>
        <relationshipName>OAC_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Remarks__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Remarks</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To_Account_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>To Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Transaction Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Transaction Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>OAC Transactions</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>OAC Transactions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OAC Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AllTransactionsController.cls
public class AllTransactionsController {
    public List<OAC_Transactions__c> transactionList{set;get;}
    
    
    public AllTransactionsController(ApexPages.StandardController controller){
        this();
    }
    
    public AllTransactionsController(){
        String accId = ApexPages.currentPage().getParameters().get('id');
        if(accId !=null)
            initializeRecords(accId);
    }
    
    private void initializeRecords(String accId){
        transactionList = [select Transaction_Date__c,Remarks__c,Transaction_Type__c,Amount__c,To_Account_Name__c from OAC_Transactions__c where From_Account_External_Id__c = :accId];
    }
    
    public PageReference cancel(){
        String accId = ApexPages.currentPage().getParameters().get('id');
        return new PageReference('/'+accId);
    }
}