objects/Relationship__c.object
<CustomObject>
    <fields>
        <fullName>Client_name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Relationships Added by Client</relationshipLabel>
        <relationshipName>Relationship_object</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Field used to store the Unique id when mapping data back to Salesforce from external system</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>ExternalId</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Owner</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ownership_of_Business__c</fullName>
        <label>Ownership of Business</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Partner_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Added as a partner of</relationshipLabel>
        <relationshipName>Relationship_object1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Relationship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RelationshipTriggerhandler_test.cls
@isTest
private class RelationshipTriggerhandler_test{
    
    static testmethod Void testrelationshipTriggerHandler(){
        
        /*Create RelationShip Object for Testing */
        Account clientAcc = new Account(name ='testabcd');
        insert clientAcc;
        
        Account partnerAcc = new Account(name ='testabcd2');
        insert partnerAcc;
        
        Contact con = new Contact(AccountId=partnerAcc.id,email='test@abcd.com',MobilePhone='5555555555',Ownership_of_Business__c=2.00, lastname='Test L Name');
        insert con;
        
        Relationship__c rel = new Relationship__c();
        rel.First_Name__c='Testrel';
        rel.Partner_Name__c = partnerAcc.id;
        rel.Client_name__c = clientAcc.Id;
        rel.Owner__c = true;
        rel.Ownership_of_Business__c = 4;
        insert rel;
        
        rel.Last_Name__c='sss';
        update rel;
        rel= [select ExternalId__c from Relationship__c where Id=:rel.id];
        System.assertEquals(true, rel.ExternalId__c!=null);     // Checking if we are getting id In assert equal 
        
    }
}