objects/Reporting_Document__c.object
<CustomObject>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CTR</fullName>
                </value>
                <value>
                    <fullName>SAR</fullName>
                </value>
                <value>
                    <fullName>Program Document</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Reporting Document</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Reporting Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reporting Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ReportingDocumentTriggerTest.cls
@isTest
public class ReportingDocumentTriggerTest {
    
    @isTest
    public static void insertCD(){
        
        Reporting_Document__c cd = new Reporting_Document__c(name='test', Document_Type__c='SAR');
        insert cd;
            
    }
    
    @isTest
    public static void inserNullCD(){
        
        Reporting_Document__c cd = new Reporting_Document__c(name=NULL, Document_Type__c='SAR');
        insert cd;
            
    }
}